### PR TITLE
refactor: include openapi-validator as a package

### PR DESCRIPTION
**Pull request by mvegter**

### CODE REVIEW

**Comment by mvegter** [comment]
@richardlau I believe that this should do the trick

**Comment by mvegter** [comment]
@rwalle61 I believe this should do the trick

**Comment by rwalle61** [comment]
Thanks @mvegter, I'm a bit busy atm but will review when I can

**Review by rwalle61 — COMMENTED** [review]
Sorry for the delay @mvegter, and thanks again for this, especially discovering the fix to make us compatible with OpenAPIResponseValidator v7!

The code looks good, see the minor comments below.

However I don't think we should merge this for several reasons that will take time to resolve. They are my fault, not yours, and I'm not asking you to fix them. I'm just being open and honest as to why they block this PR and why they will take me time to resolve.

Things blocking this PR:
1. test coverage for the Jest and Chai plugins [no longer reports on the `openapi-validator` code](https://travis-ci.com/github/openapi-library/OpenAPIValidators/builds/190738815). This is because the `openapi-validator` code is now in a separate directory. I think it's fairly easy to merge the reports though following [this for chai](https://github.com/istanbuljs/nyc/issues/1129#issuecomment-502896476) and Jest's equivalent for the Jest plugin)
2. for the same reason, mutation test coverage for the plugins [no longer report on the `openapi-validator` code](https://travis-ci.com/github/openapi-library/OpenAPIValidators/builds/190738815). However I tried and failed to fix stryker for this back in April, so we would probably have to just sacrifice much of our mutation test coverage. Mutation testing helps us simplify code a bit but it is blocking several improvements to our codebase (e.g. this PR and TypeScript), so we should just drop mutation testing.
3. although yarn workspaces makes this `packages` setup work, we need to ensure that users of e.g. jest-openapi pull in the correct version of `openapi-validator`. Ideally we'd automatically publish all 3 packages with the same version (e.g. using lerna). But until we set that up, this is a manual process liable to error

My thought process is that merging this PR will not really benefit the user. The only thing they get is that we use an updated dev dependency (`openapi-response-validator`). Merging this PR will benefit us (devs) in de-duplicating the `openapi-validator` code, but will cost us problems 1-3.

So that's why I think that although your effort has helped us, we should park this for now. What do you think?

**Comment by mvegter** [comment]
Hi @rwalle61, thanks for explaining what is blocking this pull request. At the moment we are affected (and in a way not) by your third point regarding manual releasing. The openapi-validator package.json specifies that they depend on the ` "openapi-response-validator": "^4.0.0",` which of course breaks the API without the proposed fix. This was released in the 0.9.3 release. However, the openapi-validator package itself was not released. At the moment looking at the package.json's shows a different dependency tree than the actual one fetched.

I'm not sure if labelling openapi-response-validator or openapi-schema-validator a dev dependency is correct as they are both regular if not the main dependencies of openapi-validator. That being said the new versions of these packags do not offer much to the end user of either jest or chai package. Moving the openapi-validator to its own package does result in dependabot picking up any changes so that is a win.

Both options (merging / waiting) have their own advantages and disadvantages. Point 1 is of course annoying but not that breaking due to the openapi-validator package being tested by both the chai and jest packages. I'm not sure about point 2, I'm not familiair with mutation testing. Point 3 is not limited to this pull request as it is happening right now (see above) and will be still here after merging this pull request. However, it will more centralized as there is only a single openapi-validator package.

P.S. I did do the review points so they are solved and so the coverage report link would be updated.

**Comment by rwalle61** [comment]
Superceded by https://github.com/openapi-library/OpenAPIValidators/pull/220 - thanks @mvegter for your work on this PR! I will credit you in the release notes (let me know if you wouldn't like that)

**Comment by mvegter** [comment]
> Superceded by #220 - thanks @mvegter for your work on this PR! I will credit you in the release notes (let me know if you wouldn't like that)

Sounds good to me! Very happy to see the big cleanup on master 🚀

**Comment by rwalle61** [comment]
I've just published v0.12.0 of the jest and chai plugins to npm 😄 (works for me, let me know if otherwise!)

**Pull request closed without merging**
